### PR TITLE
Jwt token

### PR DESCRIPTION
**Pull request by junyang0**
## Description

JWT Token

https://garrysjh.atlassian.net/jira/software/projects/DIP/boards/1?selectedIssue=DIP-26

### CODE REVIEW

**Comment by junyang0** [comment]
Modified frontend code for authentication.

Works and returns the corresponding JWT token.

**Comment by junyang0** [comment]
jwt.secret=eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY5NDAwODU2MSwiaWF0IjoxNjk0MDA4NTYxfQ.6UJXEaQc5kE8e8bmjDjnoyXYFbhFRlf7mij1I_iboYQ
jwt.expiration=36000000000


Add to your application.properties to test

**Comment by garrysjh** [comment]
Modify URL in main.dart when testing

For android emulators, use http://10.0.2.2:8080/api/v1 , if IOS or web http://localhost:8080/api/v1, otherwise for local connections, use local IP from ipconfig

**Comment by garrysjh** [comment]
TODO: 
1. Clean up frontend (responsiveness and input fields)
2. Frontend validation (don't accept null, etc.)

Backlog:
1. Cleanup backend validation and returning data (with snackbar?)

**Review by garrysjh — APPROVED** [review]
Working on android emu, web emu has problems but not important

**Pull request merged**
